# Generated by Django 2.2 on 2022-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseinfo',
            name='workPermitNumber',
            field=models.CharField(default=-1, max_length=45),
        ),
        migrations.AddField(
            model_name='nurseinfo',
            name='workPermitPassword',
            field=models.CharField(default=-1, max_length=45),
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='password',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='username',
            field=models.CharField(max_length=45),
        ),
    ]
