# Generated by Django 2.2 on 2022-11-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0002_auto_20221110_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadNurseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('workPermitNumber', models.CharField(default=-1, max_length=45)),
                ('workPermitPassword', models.CharField(default=-1, max_length=45)),
                ('login_jwt', models.CharField(default=-1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InfusionRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPatient', models.CharField(max_length=45)),
                ('idNurse', models.CharField(default=-1, max_length=45)),
                ('idPharmaceuticals', models.CharField(default=-1, max_length=45)),
                ('idPiercingTools', models.CharField(default=-1, max_length=45)),
                ('idIntravenous', models.CharField(default=-1, max_length=45)),
                ('InfusionDate', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='IntravenousInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntravenousName', models.CharField(max_length=45)),
                ('IntravenousDiameter', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('InpatientNumber', models.CharField(default=-1, max_length=45)),
                ('workPermitPassword', models.CharField(default=-1, max_length=45)),
                ('diagnosis', models.CharField(default=-1, max_length=45)),
                ('bedNumber', models.CharField(default=-1, max_length=45)),
                ('admissionDate', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaceuticalsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PharmaceuticalsType', models.CharField(max_length=45)),
                ('PharmaceuticalsQR', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PiercingToolsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PiercingToolsName', models.CharField(max_length=45)),
                ('PiercingToolsRetentionTime', models.CharField(default=-1, max_length=45)),
                ('PiercingApplicationScope', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='nurseinfo',
            name='login_jwt',
            field=models.CharField(default=-1, max_length=200),
        ),
    ]
