# Generated by Django 2.2 on 2022-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0003_auto_20221117_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infusionrecords',
            old_name='InfusionDate',
            new_name='InfusionDateTime',
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='login_jwt',
            field=models.CharField(default=-1, max_length=500),
        ),
    ]
