# Generated by Django 2.2 on 2022-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0004_auto_20221119_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNurse', models.CharField(default=-1, max_length=45)),
                ('location', models.CharField(default=-1, max_length=45)),
                ('hazardInfo', models.CharField(default=-1, max_length=45)),
                ('hazardDateTime', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNurse', models.CharField(default=-1, max_length=45)),
                ('location', models.CharField(default=-1, max_length=45)),
                ('inspectionInfo', models.CharField(default=-1, max_length=45)),
                ('inspectionDateTime', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NurseToPaientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurseWorkPermitNumber', models.CharField(default=-1, max_length=45)),
                ('InpatientNumber', models.CharField(default=-1, max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='infusionrecords',
            old_name='InfusionDateTime',
            new_name='infusionDateTime',
        ),
    ]
