# Generated by Django 2.2 on 2022-11-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0005_auto_20221119_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='workPermitPassword',
        ),
    ]
