# Generated by Django 2.2 on 2022-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogic', '0006_remove_patientinfo_workpermitpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='photoAddress',
            field=models.CharField(default=-1, max_length=45),
        ),
    ]
