# Generated by Django 2.2 on 2022-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadNurseBackstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head2Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurseWorkPermitNumber', models.CharField(default=-1, max_length=45)),
                ('headNurseWorkPermitNumber', models.CharField(default=-1, max_length=45)),
            ],
        ),
    ]
